# Generated by Django 5.2.8 on 2025-11-26 03:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('parent', 'Ebeveyn'), ('child', 'Çocuk')], default='parent', max_length=10, verbose_name='Kullanıcı Tipi')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil Fotoğrafı')),
                ('screen_time_limit', models.PositiveIntegerField(default=30, help_text='Günlük maksimum kullanım süresi (dakika)', verbose_name='Ekran Süresi Limiti (dk)')),
                ('bedtime_mode_enabled', models.BooleanField(default=False, verbose_name='Yatma Zamanı Modu')),
                ('bedtime_hour', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Yatma Saati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='Takma Ad')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('age', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)], verbose_name='Yaş')),
                ('gender', models.CharField(blank=True, choices=[('erkek', 'Erkek'), ('kiz', 'Kız'), ('diger', 'Belirtmek İstemiyorum')], max_length=10, verbose_name='Cinsiyet')),
                ('avatar_body', models.CharField(default='scientist', max_length=50, verbose_name='Avatar Kıyafet')),
                ('avatar_color', models.CharField(default='blue', max_length=20, verbose_name='Avatar Renk')),
                ('avatar_accessory', models.CharField(blank=True, max_length=50, verbose_name='Avatar Aksesuar')),
                ('star_dust', models.PositiveIntegerField(default=0, verbose_name='Yıldız Tozu (Puan)')),
                ('total_experiments', models.PositiveIntegerField(default=0, verbose_name='Toplam Deney')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Günlük Seri')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='En Uzun Seri')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Son Aktivite')),
                ('favorite_category', models.CharField(blank=True, max_length=50, verbose_name='Favori Kategori')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='Ses Açık')),
                ('dark_mode', models.BooleanField(default=False, verbose_name='Gece Modu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Ebeveyn')),
            ],
            options={
                'verbose_name': 'Çocuk Profili',
                'verbose_name_plural': 'Çocuk Profilleri',
                'ordering': ['nickname'],
            },
        ),
        migrations.CreateModel(
            name='DailyLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateField(auto_now_add=True, verbose_name='Giriş Tarihi')),
                ('reward_claimed', models.BooleanField(default=False, verbose_name='Ödül Alındı')),
                ('reward_type', models.CharField(blank=True, max_length=50, verbose_name='Ödül Tipi')),
                ('reward_amount', models.PositiveIntegerField(default=0, verbose_name='Ödül Miktarı')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logins', to='accounts.childprofile', verbose_name='Çocuk')),
            ],
            options={
                'verbose_name': 'Günlük Giriş',
                'verbose_name_plural': 'Günlük Girişler',
                'ordering': ['-login_date'],
                'unique_together': {('child', 'login_date')},
            },
        ),
    ]
