# Generated by Django 5.2.8 on 2025-11-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='Çocuğun mevcut seviyesi', verbose_name='Seviye'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='total_points',
            field=models.PositiveIntegerField(default=0, help_text='Tüm aktivitelerden kazanılan toplam puan', verbose_name='Toplam Puan'),
        ),
    ]
