# Generated by Django 5.2.8 on 2025-11-26 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('experiments', '0001_initial'),
        ('storymode', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Giriş'), ('logout', 'Çıkış'), ('experiment_start', 'Deney Başlattı'), ('experiment_complete', 'Deney Tamamladı'), ('card_view', 'Kart Görüntüledi'), ('story_read', 'Hikaye Okudu'), ('chat_message', 'Sohbet Mesajı'), ('badge_earned', 'Rozet Kazandı'), ('avatar_purchase', 'Avatar Satın Aldı'), ('level_up', 'Seviye Atladı')], max_length=30, verbose_name='Aktivite Türü')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Ekstra Veri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih/Saat')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Süre (saniye)')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='accounts.childprofile', verbose_name='Çocuk')),
                ('related_experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experiments.experiment', verbose_name='İlgili Deney')),
                ('related_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storymode.story', verbose_name='İlgili Hikaye')),
            ],
            options={
                'verbose_name': 'Aktivite Günlüğü',
                'verbose_name_plural': 'Aktivite Günlükleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_time_limit', models.PositiveIntegerField(default=60, verbose_name='Günlük Süre Limiti (dk)')),
                ('allowed_start_time', models.TimeField(default='08:00', verbose_name='İzin Verilen Başlangıç Saati')),
                ('allowed_end_time', models.TimeField(default='20:00', verbose_name='İzin Verilen Bitiş Saati')),
                ('allow_chatbot', models.BooleanField(default=True, verbose_name='MiniBot Sohbete İzin Ver')),
                ('allow_voice_messages', models.BooleanField(default=True, verbose_name='Sesli Mesajlara İzin Ver')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='E-posta Bildirimleri')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push Bildirimleri')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_settings', to=settings.AUTH_USER_MODEL, verbose_name='Ebeveyn')),
            ],
            options={
                'verbose_name': 'Ebeveyn Ayarları',
                'verbose_name_plural': 'Ebeveyn Ayarları',
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('total_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Toplam Süre (dk)')),
                ('experiments_completed', models.PositiveIntegerField(default=0, verbose_name='Tamamlanan Deneyler')),
                ('cards_viewed', models.PositiveIntegerField(default=0, verbose_name='Görüntülenen Kartlar')),
                ('stories_read', models.PositiveIntegerField(default=0, verbose_name='Okunan Hikayeler')),
                ('chat_messages', models.PositiveIntegerField(default=0, verbose_name='Sohbet Mesajları')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='Kazanılan Puanlar')),
                ('badges_earned', models.PositiveIntegerField(default=0, verbose_name='Kazanılan Rozetler')),
                ('top_categories', models.JSONField(blank=True, default=list, verbose_name='En Çok İlgilenilen Kategoriler')),
                ('highlights', models.TextField(blank=True, verbose_name='Öne Çıkanlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='accounts.childprofile', verbose_name='Çocuk')),
            ],
            options={
                'verbose_name': 'Günlük Rapor',
                'verbose_name_plural': 'Günlük Raporlar',
                'ordering': ['-date'],
                'unique_together': {('child', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ParentChildLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Doğrulanmış')),
                ('can_view_chat_history', models.BooleanField(default=True, verbose_name='Sohbet Geçmişini Görebilir')),
                ('can_view_activity', models.BooleanField(default=True, verbose_name='Aktiviteleri Görebilir')),
                ('notify_on_badge', models.BooleanField(default=True, verbose_name='Rozet Kazanınca Bildir')),
                ('notify_on_experiment', models.BooleanField(default=True, verbose_name='Deney Tamamlayınca Bildir')),
                ('daily_report_email', models.BooleanField(default=False, verbose_name='Günlük Rapor E-postası')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Bağlantı Tarihi')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='accounts.childprofile', verbose_name='Çocuk')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_links', to=settings.AUTH_USER_MODEL, verbose_name='Ebeveyn')),
            ],
            options={
                'verbose_name': 'Ebeveyn-Çocuk Bağlantısı',
                'verbose_name_plural': 'Ebeveyn-Çocuk Bağlantıları',
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
