# Generated by Django 5.2.8 on 2025-11-26 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('experiments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rozet Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Kodu')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('badge_type', models.CharField(choices=[('achievement', 'Başarı'), ('streak', 'Seri'), ('category', 'Kategori Uzmanı'), ('special', 'Özel')], default='achievement', max_length=20, verbose_name='Rozet Tipi')),
                ('icon', models.ImageField(upload_to='badges/', verbose_name='Rozet Görseli')),
                ('icon_locked', models.ImageField(blank=True, null=True, upload_to='badges/locked/', verbose_name='Kilitli Görsel')),
                ('requirement_type', models.CharField(help_text='Örn: experiments_completed, streak_days, category_master', max_length=50, verbose_name='Koşul Tipi')),
                ('requirement_value', models.PositiveIntegerField(default=1, help_text='Örn: 5 deney, 7 gün seri', verbose_name='Koşul Değeri')),
                ('points_reward', models.PositiveIntegerField(default=50, verbose_name='Puan Ödülü')),
                ('is_secret', models.BooleanField(default=False, verbose_name='Gizli Rozet')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('requirement_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experiments.category', verbose_name='İlgili Kategori')),
            ],
            options={
                'verbose_name': 'Rozet',
                'verbose_name_plural': 'Rozetler',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AvatarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Öğe Adı')),
                ('item_type', models.CharField(choices=[('body', 'Kıyafet'), ('accessory', 'Aksesuar'), ('background', 'Arka Plan'), ('pet', 'Evcil Hayvan')], max_length=20, verbose_name='Öğe Tipi')),
                ('image', models.ImageField(upload_to='avatar_items/', verbose_name='Görsel')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='avatar_items/previews/', verbose_name='Önizleme Görseli')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Fiyat (Yıldız Tozu)')),
                ('is_free', models.BooleanField(default=False, verbose_name='Ücretsiz')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('required_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.badge', verbose_name='Gerekli Rozet')),
            ],
            options={
                'verbose_name': 'Avatar Öğesi',
                'verbose_name_plural': 'Avatar Öğeleri',
                'ordering': ['item_type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SurpriseEgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ödül Adı')),
                ('reward_type', models.CharField(choices=[('star_dust', 'Yıldız Tozu'), ('avatar_item', 'Avatar Öğesi'), ('badge', 'Rozet')], max_length=20, verbose_name='Ödül Tipi')),
                ('star_dust_amount', models.PositiveIntegerField(default=0, verbose_name='Yıldız Tozu Miktarı')),
                ('weight', models.PositiveIntegerField(default=100, help_text='Yüksek değer = daha sık çıkar', verbose_name='Olasılık Ağırlığı')),
                ('rarity', models.CharField(choices=[('common', 'Yaygın'), ('rare', 'Nadir'), ('epic', 'Epik'), ('legendary', 'Efsanevi')], default='common', max_length=20, verbose_name='Nadirlik')),
                ('avatar_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.avataritem', verbose_name='Avatar Öğesi')),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.badge', verbose_name='Rozet')),
            ],
            options={
                'verbose_name': 'Sürpriz Yumurta Ödülü',
                'verbose_name_plural': 'Sürpriz Yumurta Ödülleri',
            },
        ),
        migrations.CreateModel(
            name='EarnedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Kazanıldı')),
                ('is_new', models.BooleanField(default=True, verbose_name='Yeni (Görülmedi)')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earners', to='gamification.badge', verbose_name='Rozet')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='accounts.childprofile', verbose_name='Çocuk')),
            ],
            options={
                'verbose_name': 'Kazanılan Rozet',
                'verbose_name_plural': 'Kazanılan Rozetler',
                'ordering': ['-earned_at'],
                'unique_together': {('child', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='OwnedAvatarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Satın Alındı')),
                ('is_equipped', models.BooleanField(default=False, verbose_name='Kullanımda')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_items', to='accounts.childprofile', verbose_name='Çocuk')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='gamification.avataritem', verbose_name='Öğe')),
            ],
            options={
                'verbose_name': 'Sahip Olunan Öğe',
                'verbose_name_plural': 'Sahip Olunan Öğeler',
                'unique_together': {('child', 'item')},
            },
        ),
    ]
