# Generated by Django 5.2.8 on 2025-11-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='badges/', verbose_name='Rozet Görseli (Opsiyonel)'),
        ),
        migrations.AddField(
            model_name='badge',
            name='rarity',
            field=models.CharField(choices=[('common', 'Yaygın'), ('rare', 'Nadir'), ('epic', 'Destansı'), ('legendary', 'Efsanevi')], default='common', max_length=20, verbose_name='Nadirlik'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(default='🏆', help_text='Örn: 🔬, 🚀, 🧪, 👑', max_length=10, verbose_name='Rozet İkonu (Emoji)'),
        ),
    ]
