# Generated by Django 5.2.8 on 2025-11-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_badge_icon_image_badge_rarity_alter_badge_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='avataritem',
            name='icon',
            field=models.CharField(default='🎁', help_text='Örn: 🎩, 👓, 🌈, 🐕', max_length=10, verbose_name='Öğe İkonu (Emoji)'),
        ),
        migrations.AddField(
            model_name='avataritem',
            name='rarity',
            field=models.CharField(choices=[('common', 'Yaygın'), ('rare', 'Nadir'), ('epic', 'Epik'), ('legendary', 'Efsanevi')], default='common', max_length=20, verbose_name='Nadirlik'),
        ),
        migrations.AlterField(
            model_name='avataritem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_items/', verbose_name='Görsel'),
        ),
    ]
