# Generated by Django 5.2.8 on 2025-11-26 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('experiments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('context_type', models.CharField(blank=True, help_text='experiment, story, general', max_length=50, verbose_name='Bağlam Tipi')),
                ('context_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bağlam ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='accounts.childprofile', verbose_name='Çocuk')),
            ],
            options={
                'verbose_name': 'Sohbet Oturumu',
                'verbose_name_plural': 'Sohbet Oturumları',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Çocuk'), ('assistant', 'MiniBot'), ('system', 'Sistem')], max_length=20, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='Mesaj İçeriği')),
                ('is_voice', models.BooleanField(default=False, verbose_name='Sesli Mesaj')),
                ('should_speak', models.BooleanField(default=True, verbose_name='Sesli Okuma')),
                ('has_emoji', models.BooleanField(default=False, verbose_name='Emoji İçeriyor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderildi')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession', verbose_name='Oturum')),
            ],
            options={
                'verbose_name': 'Sohbet Mesajı',
                'verbose_name_plural': 'Sohbet Mesajları',
                'ordering': ['session', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MiniBotHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('experiment_start', 'Deney Başlangıcı'), ('experiment_stuck', 'Takılma'), ('experiment_complete', 'Deney Tamamlama'), ('idle', 'Hareketsizlik'), ('first_visit', 'İlk Ziyaret')], max_length=30, verbose_name='Tetikleyici')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('animation', models.CharField(blank=True, choices=[('wave', 'El Sallama'), ('bounce', 'Zıplama'), ('think', 'Düşünme'), ('celebrate', 'Kutlama')], max_length=50, verbose_name='Animasyon')),
                ('delay_seconds', models.PositiveIntegerField(default=5, help_text='Kaç saniye sonra gösterilsin', verbose_name='Gecikme (sn)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Öncelik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='experiments.category', verbose_name='Kategori')),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='experiments.experiment', verbose_name='Deney')),
            ],
            options={
                'verbose_name': 'MiniBot İpucu',
                'verbose_name_plural': 'MiniBot İpuçları',
                'ordering': ['trigger', 'order'],
            },
        ),
    ]
