# Generated by Django 5.2.8 on 2025-11-26 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Sohbet Mesajı', 'verbose_name_plural': 'Sohbet Mesajları'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_user',
            field=models.BooleanField(default=True, verbose_name='Kullanıcı Mesajı'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Mesaj'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Mesaj İçeriği'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'Çocuk'), ('assistant', 'MiniBot'), ('system', 'Sistem')], default='user', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession', verbose_name='Oturum'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='accounts.childprofile', verbose_name='Çocuk'),
        ),
    ]
