# Generated by Django 5.2.8 on 2025-11-26 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('experiments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Hikaye Başlığı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Kodu')),
                ('description', models.TextField(verbose_name='Kısa Açıklama')),
                ('cover_image', models.ImageField(upload_to='stories/covers/', verbose_name='Kapak Görseli')),
                ('audio_intro', models.FileField(blank=True, null=True, upload_to='audio/stories/', verbose_name='Sesli Giriş')),
                ('estimated_time', models.PositiveIntegerField(default=10, verbose_name='Tahmini Süre (dk)')),
                ('points', models.PositiveIntegerField(default=20, verbose_name='Kazanılacak Puan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experiments.category', verbose_name='İlgili Kategori')),
            ],
            options={
                'verbose_name': 'Hikaye',
                'verbose_name_plural': 'Hikayeler',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Sayfa Başlığı')),
                ('content', models.TextField(help_text='Çocuğa gösterilecek metin', verbose_name='İçerik')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/pages/', verbose_name='Sayfa Görseli')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/stories/pages/', verbose_name='Sesli Okuma')),
                ('animation', models.CharField(blank=True, choices=[('fade', 'Belirme'), ('slide', 'Kayma'), ('bounce', 'Zıplama'), ('sparkle', 'Parıltı')], max_length=50, verbose_name='Animasyon')),
                ('science_fact', models.TextField(blank=True, help_text='Bu sayfada öğretilen bilimsel kavram', verbose_name='Bilim Bilgisi')),
                ('is_start', models.BooleanField(default=False, verbose_name='Başlangıç Sayfası')),
                ('is_ending', models.BooleanField(default=False, verbose_name='Bitiş Sayfası')),
                ('ending_type', models.CharField(blank=True, choices=[('good', 'İyi Son'), ('neutral', 'Nötr Son'), ('learning', 'Öğrenme Sonu')], max_length=20, verbose_name='Bitiş Türü')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='storymode.story', verbose_name='Hikaye')),
            ],
            options={
                'verbose_name': 'Hikaye Sayfası',
                'verbose_name_plural': 'Hikaye Sayfaları',
                'ordering': ['story', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StoryChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Seçenek Metni')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='İkon (Emoji)')),
                ('is_correct', models.BooleanField(default=True, verbose_name='Doğru Seçenek')),
                ('feedback', models.CharField(blank=True, max_length=200, verbose_name='Geri Bildirim')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('next_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_choices', to='storymode.storypage', verbose_name='Sonraki Sayfa')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='storymode.storypage', verbose_name='Sayfa')),
            ],
            options={
                'verbose_name': 'Hikaye Seçeneği',
                'verbose_name_plural': 'Hikaye Seçenekleri',
                'ordering': ['page', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('ending_reached', models.CharField(blank=True, max_length=20, verbose_name='Ulaşılan Son')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_progress', to='accounts.childprofile', verbose_name='Çocuk')),
                ('current_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storymode.storypage', verbose_name='Mevcut Sayfa')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='storymode.story', verbose_name='Hikaye')),
            ],
            options={
                'verbose_name': 'Hikaye İlerlemesi',
                'verbose_name_plural': 'Hikaye İlerlemeleri',
                'unique_together': {('child', 'story')},
            },
        ),
    ]
