# Generated by Django 5.2.8 on 2025-11-27 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_childprofile_level_childprofile_total_points'),
        ('storymode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kitap Başlığı')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('cover_image', models.ImageField(upload_to='interactive_books/covers/', verbose_name='Kapak Görseli')),
                ('age_range', models.CharField(default='4-6', max_length=20, verbose_name='Yaş Aralığı')),
                ('estimated_time', models.PositiveIntegerField(default=10, verbose_name='Tahmini Süre (dk)')),
                ('points', models.PositiveIntegerField(default=25, verbose_name='Kazanılacak Puan')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'İnteraktif Kitap',
                'verbose_name_plural': 'İnteraktif Kitaplar',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Kart Başlığı')),
                ('category', models.CharField(choices=[('animals', '🐾 Hayvanlar'), ('plants', '🌱 Bitkiler'), ('space', '🚀 Uzay'), ('body', '🫀 Vücut'), ('weather', '🌤️ Hava'), ('colors', '🎨 Renkler'), ('shapes', '🔷 Şekiller'), ('numbers', '🔢 Sayılar'), ('science', '🔬 Bilim'), ('nature', '🌿 Doğa')], max_length=20, verbose_name='Kategori')),
                ('front_text', models.CharField(help_text='Kartın ön yüzünde gösterilecek soru/kelime', max_length=200, verbose_name='Ön Yüz Metni')),
                ('back_text', models.TextField(help_text='Kartın arka yüzünde gösterilecek cevap/açıklama', verbose_name='Arka Yüz Metni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/images/', verbose_name='Kart Görseli')),
                ('emoji', models.CharField(default='📚', max_length=10, verbose_name='Emoji İkonu')),
                ('audio_pronunciation', models.FileField(blank=True, null=True, upload_to='audio/cards/', verbose_name='Sesli Telaffuz')),
                ('fun_fact', models.TextField(blank=True, help_text='Karta ait ilginç bir bilgi', verbose_name='Eğlenceli Bilgi')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Kolay'), (2, 'Orta'), (3, 'Zor')], default=1, verbose_name='Zorluk')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Öğrenme Kartı',
                'verbose_name_plural': 'Öğrenme Kartları',
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MemoryMatchGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Oyun Başlığı')),
                ('game_type', models.CharField(choices=[('image_match', '🖼️ Görsel Eşleştirme'), ('word_image', '📝 Kelime-Görsel'), ('emoji_word', '😊 Emoji-Kelime'), ('sound_image', '🔊 Ses-Görsel'), ('shadow_match', '👤 Gölge Eşleştirme')], max_length=20, verbose_name='Oyun Türü')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('grid_size', models.CharField(choices=[('2x2', '2x2 (4 kart)'), ('2x3', '2x3 (6 kart)'), ('3x4', '3x4 (12 kart)'), ('4x4', '4x4 (16 kart)'), ('4x5', '4x5 (20 kart)')], default='4x3', max_length=10, verbose_name='Izgara Boyutu')),
                ('time_limit', models.PositiveIntegerField(default=120, verbose_name='Süre Limiti (saniye)')),
                ('points', models.PositiveIntegerField(default=15, verbose_name='Kazanılacak Puan')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Kolay'), (2, 'Orta'), (3, 'Zor')], default=1, verbose_name='Zorluk')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hafıza Oyunu',
                'verbose_name_plural': 'Hafıza Oyunları',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WordPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Bulmaca Başlığı')),
                ('puzzle_type', models.CharField(choices=[('fill_blank', '📝 Boşluk Doldurma'), ('word_scramble', '🔀 Harf Karıştırma'), ('word_search', '🔍 Kelime Arama'), ('rhyme', '🎵 Kafiye Bulma'), ('opposite', '↔️ Zıt Anlamlı')], max_length=20, verbose_name='Bulmaca Türü')),
                ('question', models.TextField(verbose_name='Soru/İpucu')),
                ('answer', models.CharField(max_length=100, verbose_name='Doğru Cevap')),
                ('hint', models.CharField(blank=True, max_length=200, verbose_name='İpucu')),
                ('emoji', models.CharField(default='❓', max_length=10, verbose_name='Emoji')),
                ('image', models.ImageField(blank=True, null=True, upload_to='puzzles/images/', verbose_name='Görsel İpucu')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Kolay'), (2, 'Orta'), (3, 'Zor')], default=1, verbose_name='Zorluk')),
                ('points', models.PositiveIntegerField(default=10, verbose_name='Puan')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kelime Bulmacası',
                'verbose_name_plural': 'Kelime Bulmacaları',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(verbose_name='Sayfa Numarası')),
                ('background_image', models.ImageField(upload_to='interactive_books/pages/', verbose_name='Arka Plan Görseli')),
                ('text_content', models.TextField(blank=True, verbose_name='Metin İçeriği')),
                ('text_position', models.CharField(choices=[('top', 'Üstte'), ('bottom', 'Altta'), ('left', 'Solda'), ('right', 'Sağda'), ('center', 'Ortada')], default='bottom', max_length=20, verbose_name='Metin Pozisyonu')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/books/', verbose_name='Sesli Okuma')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='storymode.interactivebook', verbose_name='Kitap')),
            ],
            options={
                'verbose_name': 'Kitap Sayfası',
                'verbose_name_plural': 'Kitap Sayfaları',
                'ordering': ['book', 'page_number'],
                'unique_together': {('book', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='InteractiveHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot_type', models.CharField(choices=[('info', '💡 Bilgi'), ('animation', '✨ Animasyon'), ('sound', '🔊 Ses'), ('quiz', '❓ Soru'), ('navigate', '➡️ Geçiş')], max_length=20, verbose_name='Tip')),
                ('x_position', models.FloatField(verbose_name='X Pozisyonu (%)')),
                ('y_position', models.FloatField(verbose_name='Y Pozisyonu (%)')),
                ('width', models.FloatField(default=10, verbose_name='Genişlik (%)')),
                ('height', models.FloatField(default=10, verbose_name='Yükseklik (%)')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Başlık')),
                ('content', models.TextField(blank=True, verbose_name='İçerik/Açıklama')),
                ('emoji', models.CharField(default='👆', max_length=10, verbose_name='Emoji')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/hotspots/', verbose_name='Ses')),
                ('animation_class', models.CharField(blank=True, choices=[('bounce', 'Zıplama'), ('shake', 'Sallanma'), ('spin', 'Dönme'), ('pulse', 'Nabız'), ('wiggle', 'Kıpırdama')], max_length=50, verbose_name='Animasyon')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Görünür')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='storymode.bookpage', verbose_name='Sayfa')),
            ],
            options={
                'verbose_name': 'Etkileşim Noktası',
                'verbose_name_plural': 'Etkileşim Noktaları',
                'ordering': ['page', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MatchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_a', models.CharField(help_text='Emoji, kelime veya görsel URL', max_length=200, verbose_name='İçerik A')),
                ('content_a_type', models.CharField(choices=[('emoji', 'Emoji'), ('text', 'Metin'), ('image', 'Görsel'), ('audio', 'Ses')], default='emoji', max_length=20, verbose_name='A Tipi')),
                ('content_b', models.CharField(help_text='Eşleşen içerik', max_length=200, verbose_name='İçerik B')),
                ('content_b_type', models.CharField(choices=[('emoji', 'Emoji'), ('text', 'Metin'), ('image', 'Görsel'), ('audio', 'Ses')], default='text', max_length=20, verbose_name='B Tipi')),
                ('image_a', models.ImageField(blank=True, null=True, upload_to='memory_game/cards/', verbose_name='Görsel A')),
                ('image_b', models.ImageField(blank=True, null=True, upload_to='memory_game/cards/', verbose_name='Görsel B')),
                ('order', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='storymode.memorymatchgame', verbose_name='Oyun')),
            ],
            options={
                'verbose_name': 'Eşleştirme Kartı',
                'verbose_name_plural': 'Eşleştirme Kartları',
                'ordering': ['game', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StoryGameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards_learned', models.PositiveIntegerField(default=0, verbose_name='Öğrenilen Kartlar')),
                ('memory_games_played', models.PositiveIntegerField(default=0, verbose_name='Oynanan Hafıza Oyunları')),
                ('memory_games_won', models.PositiveIntegerField(default=0, verbose_name='Kazanılan Hafıza Oyunları')),
                ('puzzles_solved', models.PositiveIntegerField(default=0, verbose_name='Çözülen Bulmacalar')),
                ('books_completed', models.PositiveIntegerField(default=0, verbose_name='Tamamlanan Kitaplar')),
                ('total_reading_time', models.PositiveIntegerField(default=0, verbose_name='Toplam Okuma Süresi (dk)')),
                ('total_game_time', models.PositiveIntegerField(default=0, verbose_name='Toplam Oyun Süresi (dk)')),
                ('earned_badges', models.JSONField(default=list, verbose_name='Kazanılan Rozetler')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Son Aktivite')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_game_progress', to='accounts.childprofile', verbose_name='Çocuk')),
            ],
            options={
                'verbose_name': 'Oyun İlerlemesi',
                'verbose_name_plural': 'Oyun İlerlemeleri',
            },
        ),
    ]
